name: Deploy myapp to MicroK8s

on:
  push:
    branches: [ main ]
  create:
    tags:
      - '*'

jobs:
  deploy:
    environment: env
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{secrets.DOCKER_USERNAME}}/myapp
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "${{secrets.DOCKER_USERNAME}}/myapp:v${{ github.ref_name }}"
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Set up Kubernetes environment
        run: |
          mkdir -p ~/.kube
          echo "${{secrets.KUBECONFIG}}" > ~/.kube/config
      - name: Create namespace if it doesn't exist
        run: |
          kubectl get namespace myapp || kubectl create namespace myapp
      - name: Deploy to Kubernetes
        run: |
          export IMAGE_TAG=v${{ github.ref_name }}
          envsubst < kubernetes/deployment.yaml > kubernetes/deployment_temp.yaml
          kubectl apply -f kubernetes/deployment_temp.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/ingress.yaml
          kubectl apply -f kubernetes/hpa.yaml